### ISSUE TITLE
Certain days don't load sensitivity/ringmap

### ISSUE THREAD

**Issue by ljgray** [chime-experiment/bondia#146]
- 2179
- 2810

**Comment by jmaceachern** [comment]
- 2041
- 2439
- 2753

**Comment by sjforeman** [comment]
- 2047
- 2060
- 2099
- 2106
- 2107
- 2110
- 2115
- 2118
- 2119
- 2123
- 2126
- 2133
- 2134

Also, as of 3pm PT on Nov. 15, it's still true that none of the days in previous comments load their ringmaps or sensitivity plots

**Comment by ljgray** [comment]
This should be addressed in the most recent PR and deployed live
