### ISSUE TITLE
No menus in Firefox or Safari

### ISSUE THREAD

**Issue by ashill** [chime-experiment/bondia#35]
The menus do not appear properly in either Safari 13.1.2 or Firefox 78.0.2 on macOS 10.15.6. They do appear properly in Chrome.

It doesn't immediately appear that there's missing functionality in Safari; the select data content is just displayed oddly up top. In Firefox, the select data functionality appears to be missing.

Safari:
![Screen Shot 2020-07-29 at 13 33 01](https://user-images.githubusercontent.com/4828043/88850524-5d639000-d1a0-11ea-8374-bad7f9a03c7a.png)

Firefox:
![Screen Shot 2020-07-29 at 13 32 50](https://user-images.githubusercontent.com/4828043/88850541-60f71700-d1a0-11ea-814d-fe6ecafed601.png)

Chrome:
![Screen Shot 2020-07-29 at 13 36 39](https://user-images.githubusercontent.com/4828043/88850667-8f74f200-d1a0-11ea-9e7c-6b3fa4ebfe6d.png)

**Comment by nritsche** [comment]
Thanks a lot for the bug report @ashill 
I didn't manage to replicate this with Safari 13.1.1 and Firefox 78.0 on MacOS Catalina.
Please let me know if this problem persists and have another look at if there's any chance you browser, machine or network stopped the page from loading the drawer menu from https://unpkg.com/@material/mwc-drawer@0.17.2/mwc-drawer.js?module

**Comment by ashill** [comment]
Hi @nritsche 
The menu now appears and appears to work in both Safari and Firefox; did you change anything? However, logged in as myself (ashill), it now says "User: rick" in all three browsers. I don't see a logout option. The person in the upper right corner (which looks like it should be where account stuff happens) doesn't do anything when I click on it (in any of the three browsers).

![Screen Shot 2020-07-29 at 15 58 18](https://user-images.githubusercontent.com/4828043/88862135-59da0400-d1b4-11ea-9c56-1fe01f633b37.png)

**Comment by nritsche** [comment]
> However, logged in as myself (ashill), it now says "User: rick" in all three browsers. I don't see a logout option. The person in the upper right corner (which looks like it should be where account stuff happens) doesn't do anything when I click on it (in any of the three browsers).

I opened #37 for this.

**Comment by ljgray** [comment]
It seems like this was resolved
