### ISSUE TITLE
Sort lsd index after indexing new data

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/bondia#61]
If old days get added to the index, they will end up at the end of it. The list of days in the selector is messed up afterwards and the user might get a random old date every time they enter a decision.

**Comment by jrs65** [comment]
I think this isn't that high priority provided #62 is done.

**Comment by nritsche** [comment]
> I think this isn't that high priority provided #62 is done.

I think it is, because we still rely on the data being sorted correctly.

**Comment by jrs65** [comment]
Okay, well provided #62 gets fixed soon. At the moment, it's too frustrating for me to use :(
